# Generated by Django 5.2 on 2025-05-15 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0003_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='email',
            new_name='parents_name',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='name',
            new_name='student_name',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='message',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='subject',
        ),
        migrations.AddField(
            model_name='contactus',
            name='child_date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='parents_mobile_number',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactus',
            name='select_class_looking_for',
            field=models.CharField(choices=[('P.Nursery', 'P.Nursery'), ('Nursery', 'Nursery')], default=1),
            preserve_default=False,
        ),
    ]
