# Generated by Django 5.2 on 2025-05-20 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0004_rename_email_contactus_parents_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateField(default='2025-02-22'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactus',
            name='select_class_looking_for',
            field=models.CharField(choices=[('P.Nursery', 'P.Nursery'), ('Nursery', 'Nursery'), ('UKG', 'UKG'), ('1ST', '1ST'), ('2ND', '2ND'), ('3RD', '3RD'), ('4TH', '4TH'), ('5TH', '5TH')]),
        ),
    ]
