# Generated by Django 5.2 on 2025-05-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customadmin", "0004_rename_email_contactus_parents_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("date", models.DateField(auto_now_add=True)),
                ("file", models.FileField(blank=True, null=True, upload_to="notices/")),
            ],
            options={
                "verbose_name": "Notice",
                "verbose_name_plural": "Notices",
                "ordering": ["-date"],
            },
        ),
        migrations.AddField(
            model_name="event",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="start_date",
            field=models.DateField(default="2025-05-22"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contactus",
            name="select_class_looking_for",
            field=models.CharField(
                choices=[
                    ("P.Nursery", "P.Nursery"),
                    ("Nursery", "Nursery"),
                    ("UKG", "UKG"),
                    ("1ST", "1ST"),
                    ("2ND", "2ND"),
                    ("3RD", "3RD"),
                    ("4TH", "4TH"),
                    ("5TH", "5TH"),
                ]
            ),
        ),
    ]
