# Generated by Django 5.2 on 2025-05-23 07:36

import customadmin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customadmin", "0005_notice_event_end_date_event_start_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="gallery_video/",
                validators=[customadmin.models.validate_mp4],
            ),
        ),
        migrations.AlterField(
            model_name="contactus",
            name="select_class_looking_for",
            field=models.CharField(
                choices=[
                    ("P.Nursery", "P.Nursery"),
                    ("Nursery", "Nursery"),
                    ("LKG", "LKG"),
                    ("UKG", "UKG"),
                    ("1ST", "1ST"),
                    ("2ND", "2ND"),
                    ("3RD", "3RD"),
                    ("4TH", "4TH"),
                    ("5TH", "5TH"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="gallery_images/"),
        ),
        migrations.AlterField(
            model_name="notice",
            name="date",
            field=models.DateField(),
        ),
    ]
