# Generated by Django 5.2 on 2025-06-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0007_gallery_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Our_Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='OUr_Vision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.TextField(blank=True)),
            ],
        ),
    ]
